In [2]:
with open("input/22", "r") as fp:
    txt = fp.read()[:-1]

In [1]:
txt_test = """1,0,1~1,2,1
0,0,2~2,0,2
0,2,3~2,2,3
0,0,4~0,2,4
2,0,5~2,2,5
0,1,6~2,1,6
1,1,8~1,1,9"""

#### Process input

In [3]:
def process_line(line):
    a, b = line.split("~")
    C1 = list(map(int, a.split(",")))
    C2 = list(map(int, b.split(",")))
    return C1, C2

def process_puzzle(ttt):
    lines = ttt.split('\n')
    parts = list(map(process_line, lines))
    X1 = np.array(list(map(lambda x: x[0], parts)))
    X2 = np.array(list(map(lambda x: x[1], parts)))
    return X1, X2


Ground level: z=1


##### Print / debug

In [13]:
def print_matrix(X1, X2):
    
    mz = 0
    Mz = max(X1[:, 1].max(), X2[:, 1].max()) + 1
    
    mx = 0
    Mx = max(X1[:, 0].max(), X2[:, 0].max()) + 1
    
    M_tot = np.zeros((Mz - mz, Mx - mx))
    for idx, ((x0, z0), (x1, z1)) in enumerate(zip(X1, X2)):
        M_tot[z0:z1+1, x0:x1+1] = idx + 1
        
    return M_tot[::-1]
    

def print_over_xz(X1, X2):
    
    X1 = X1[:, [0, 2]]
    X2 = X2[:, [0, 2]]
    
    return print_matrix(X1, X2)
    

def print_over_yz(X1, X2):
    
    X1 = X1[:, [1, 2]]
    X2 = X2[:, [1, 2]]
    
    return print_matrix(X1, X2)
    

In [18]:
def create_tensor(X1, X2):
    
    a, b, c = X2.max(axis=0)
    
    M_tot = np.zeros((a+1, b+1, c+1))
    
    for idx, ((x0, y0, z0), (x1, y1, z1)) in enumerate(zip(X1, X2)):
        M_tot[z0:z1+1, x0:x1+1, y0:y1+1] = idx + 1
        
    return M_tot

### Sort bricks by z

In [112]:
def check_coordinates(a0, a1, b0, b1):
    """
    A #######a1
    B          b0#####
    
    A         a0####a1
    B b0####b1
    
    A         a0####a1
    B     b0####b1
    
    A    a0####a1
    B         b0####b1
    
    A        a0####a1
    B     b0##########b1
    
    
    
    
    """
    
    if (a1 < b0) | (b1 < a0):
        #if (a1 + 1 < b0) | (b1+1 < a0):
        return False
    
    else:
        return True
    
    

def is_connected(x1a, x1b, x2a, x2b):
    """
    xa: brick above
    xb: brick bellow
    """
    
    if x1a[2] == x2b[2] + 1: # Si Z+ touche Z-, connection possible
        # Il y a possiblement un contact si l'une des coordinates x / y se recouvrent
        T1 = check_coordinates(x1a[0], x1b[0], x2a[0], x2b[0])
        T2 = check_coordinates(x1a[1], x1b[1], x2a[1], x2b[1])
        # Si les deux coordinnées se recouvrent, alors OK
        return T1 & T2
    
    else:
        return False
    
    

# Processing common

In [135]:
X1, X2 = process_puzzle(txt)
print(X1.min(axis=0))
print(X1.max(axis=0))
print(X2.min(axis=0))
print(X2.max(axis=0))


# Sort bricks by z
order = np.argsort(X1[:, 2])
X1 = X1[order]
X2 = X2[order]

[0 0 1]
[  9   9 305]
[0 0 1]
[  9   9 305]


In [136]:
for idx, (x1a, x2a) in enumerate(zip(X1, X2)):
    
    print(idx)
    FLAG = False
    while FLAG == False:
        if x1a[2] == 1:
            print("\tbottom")
            break
            
        msk = X2[:, 2] + 1 == x1a[2]
        for x1b, x2b in zip(X1[msk], X2[msk]):
            FLAG = FLAG | is_connected(x1a, x2a, x1b, x2b)
        
        if FLAG == False:
            # Modify X1 / X2 in place. x1a are reference to it
            x1a[2] = x1a[2] - 1
            x2a[2] = x2a[2] - 1
            print("\tMove down")
        
        else:
            print("\tOK")
            break
            
    

0
	bottom
1
	bottom
2
	bottom
3
	bottom
4
	bottom
5
	bottom
6
	bottom
7
	Move down
	bottom
8
	OK
9
	OK
10
	Move down
	bottom
11
	Move down
	Move down
	bottom
12
	Move down
	OK
13
	Move down
	Move down
	bottom
14
	Move down
	OK
15
	Move down
	Move down
	bottom
16
	Move down
	Move down
	bottom
17
	Move down
	Move down
	bottom
18
	Move down
	Move down
	bottom
19
	Move down
	Move down
	bottom
20
	Move down
	OK
21
	Move down
	Move down
	OK
22
	Move down
	Move down
	OK
23
	OK
24
	Move down
	OK
25
	Move down
	OK
26
	Move down
	Move down
	OK
27
	Move down
	OK
28
	Move down
	Move down
	OK
29
	Move down
	Move down
	Move down
	OK
30
	Move down
	Move down
	Move down
	Move down
	OK
31
	Move down
	Move down
	Move down
	Move down
	OK
32
	Move down
	Move down
	Move down
	OK
33
	Move down
	Move down
	OK
34
	Move down
	Move down
	Move down
	Move down
	OK
35
	Move down
	Move down
	Move down
	OK
36
	Move down
	Move down
	Move down
	Move down
	OK
37
	Move down
	Move down
	Move down
	Move down
	OK
38
	Move 

	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	OK
298
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	OK
299
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move

	Move down
	OK
576
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	OK
577
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move

	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	OK
779
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	M

	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	OK
939
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	M

	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down

	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down
	Move down

# Part 1

In [137]:
print(X1.min(axis=0))
print(X1.max(axis=0))
print(X2.min(axis=0))
print(X2.max(axis=0))

order = np.argsort(X1[:, 2])
X1 = X1[order]
X2 = X2[order]

[0 0 1]
[  9   9 155]
[0 0 1]
[  9   9 155]


#### Check which ones are supported

In [138]:
lst_necessary = []

for idx, (x1a, x2a) in enumerate(zip(X1, X2)):
    if x1a[2] == 1:
        print(idx, "bottom")
        continue
    
    cnt_under = []
    msk = X2[:, 2] + 1 == x1a[2]
    for x1b, x2b, jdx in zip(X1[msk], X2[msk], np.where(msk)[0]):
        if is_connected(x1a, x2a, x1b, x2b):
            cnt_under.append(jdx)

    print(cnt_under)
    if len(cnt_under) == 1:
        lst_necessary.extend(cnt_under)
            
    

0 bottom
1 bottom
2 bottom
3 bottom
4 bottom
5 bottom
6 bottom
7 bottom
8 bottom
9 bottom
10 bottom
11 bottom
12 bottom
13 bottom
14 bottom
15 bottom
[5]
[4]
[14]
[4]
[11, 13]
[12]
[10]
[9, 11, 13]
[14]
[1]
[22]
[18]
[22]
[19]
[22]
[25]
[21]
[24]
[23]
[20]
[21]
[28, 30]
[26]
[27]
[31]
[28]
[26]
[34]
[0]
[26]
[43]
[37]
[44]
[42]
[39]
[37]
[42]
[42]
[15]
[38]
[38]
[39]
[50]
[46]
[49]
[54]
[56]
[62]
[62]
[59]
[60]
[61]
[67]
[64]
[67]
[63]
[71]
[71]
[69]
[68, 70]
[75]
[73]
[74]
[72]
[75]
[73]
[74]
[72]
[77]
[77]
[77]
[78]
[81]
[79, 81]
[79]
[83]
[82]
[86]
[85]
[88]
[90]
[85]
[84, 91]
[90]
[90]
[97]
[98]
[100]
[97]
[94]
[100]
[99]
[95]
[92]
[94]
[101]
[103]
[110]
[109]
[104, 105]
[106]
[109]
[108]
[106, 109]
[104, 105]
[118]
[117]
[116]
[120]
[116]
[116]
[120]
[115]
[121]
[121]
[122]
[128]
[126]
[127]
[134]
[132]
[130]
[129]
[96]
[135]
[135]
[137]
[139]
[139]
[144]
[143]
[144]
[144]
[142]
[142]
[141]
[140]
[140]
[140]
[154]
[154]
[153]
[151]
[152]
[147]
[148]
[150]
[145]
[148]
[146]
[145]
[

In [139]:
print("Part 1: {}".format(len(X1) - len(set(lst_necessary))))

Part 1: 403


In [88]:
# 523 too high
# 453 too high
# 427 too high

# Part 2: 

In [140]:
def eval_brick_down(X1r, X2r, idx):
    # Remove the brick
    X1 = np.concatenate([X1r[:idx], X1r[idx+1:]]).copy()
    X2 = np.concatenate([X2r[:idx], X2r[idx+1:]]).copy()

    
    cnt = 0
    for idx, (x1a, x2a) in enumerate(zip(X1, X2)):
        FLAG_MOVE = False
        FLAG = False
        while FLAG == False:
            if x1a[2] == 1:
                break

            msk = X2[:, 2] + 1 == x1a[2]
            for x1b, x2b in zip(X1[msk], X2[msk]):
                FLAG = FLAG | is_connected(x1a, x2a, x1b, x2b)

            if FLAG == False:
                # Modify X1 / X2 in place. x1a are reference to it
                x1a[2] = x1a[2] - 1
                x2a[2] = x2a[2] - 1
                FLAG_MOVE = True

            else:
                break
                
        if FLAG_MOVE:
            cnt += 1
            
    return cnt

In [141]:
tot = 0
for idx in range(len(X1)):
    v = eval_brick_down(X1, X2, idx)
    tot += v

In [142]:
print("Part 2: {}".format(tot))

Part 2: 70189
