In [14]:
txt_test = """19, 13, 30 @ -2,  1, -2
18, 19, 22 @ -1, -1, -2
20, 25, 34 @ -2, -2, -4
12, 31, 28 @ -1, -2, -1
20, 19, 15 @  1, -5, -3"""


In [15]:
with open("input/24", "r") as fp:
    txt = fp.read()[:-1]

In [16]:
def process_input(ttt):
    lines = ttt.split('\n')
    results = []
    for line in lines:
        P, V = line.split(" @ ")
        P = np.array(list(map(int, P.split(","))))
        V = np.array(list(map(int, V.split(","))))
        results.append((P, V))
        
    return results

In [51]:
txt_in = txt
puzzle = process_input(txt_in)

In [53]:
puzzle

[(array([233210433951170, 272655040388795, 179982504986147]),
  array([ 39, -98, 166])),
 (array([385274025881243, 351578921558552, 375160114124378]),
  array([-71, -36,  -9])),
 (array([298962016918939, 322446494312107, 293073189215975]),
  array([36,  8, 96])),
 (array([201717428991179, 262965089923292, 196011482381270]),
  array([  92, -490, -114])),
 (array([247277712435905, 218345997267326, 196010243400590]),
  array([-165,  -58,  -21])),
 (array([352675244632049, 554364732018242, 152625975899360]),
  array([ -14, -223,  247])),
 (array([324422391745634, 227138986518940, 108773241649847]),
  array([-47,  91, 312])),
 (array([313067186829719, 462648141629189, 246008354182145]),
  array([ -32, -268,  104])),
 (array([248189680078635, 407471031162962, 290189220302863]),
  array([  84, -111,   82])),
 (array([199505021061112, 177980659229372, 175893468794335]),
  array([  75,  219, -136])),
 (array([323521328529479, 153391146336101, 520509666624452]),
  array([   8,  190, -153])),
 (a

# Part 1

In [52]:
puzzle1 = []
for P, V in puzzle:
    puzzle1.append((P[:2], V[:2]))

## Test

In [49]:
k_min, k_max = 7, 27

for idx, (P1, V1) in enumerate(puzzle1):
    for jdx, (P2, V2) in enumerate(puzzle1[:idx]):
        # Check if y positions are differnet and if they go into the same direction
        DP = P2 - P1
        
        A0 = DP[1] / V1[1] - DP[0] / V2[0] * V2[1] / V1[1]
        A1 = 1 - V2[1] * V1[0] / (V1[1] * V2[0])
        
        
        if A1 == 0:
            continue
            
            
        b = A0 / A1
        a = (-DP[0] + b * V1[0])/V2[0]
        
        if (b < 0) | (a < 0):
            # No negative time allowed
            print("PAST", idx, jdx, P1, P2)
            continue
            
        P1x = P1 + b * V1
        P2x = P2 + a * V2
        
        #print(a, b)
        #print("\t=>", P1x, P2x) # Check
        print(idx, jdx)
        print(P1, V1, "||", P2, V2)
        print("\ttime", a, b)
        print("\t=>", P1x, P2x) # Check
        if (P1x[0] >= k_min) & (P1x[1] >= k_min) & (P1x[0] <= k_max) & (P1x[0] <= k_max):
            print("\tINSIDE")
        else:
            print("\tOUTSIDE")

1 0
[18 19] [-1 -1] || [19 13] [-2  1]
	time 2.333333333333333 3.6666666666666665
	=> [14.33333333 15.33333333] [14.33333333 15.33333333]
	INSIDE
2 0
[20 25] [-2 -2] || [19 13] [-2  1]
	time 3.666666666666667 4.166666666666667
	=> [11.66666667 16.66666667] [11.66666667 16.66666667]
	INSIDE
3 0
[12 31] [-1 -2] || [19 13] [-2  1]
	time 6.4 5.8
	=> [ 6.2 19.4] [ 6.2 19.4]
	OUTSIDE
3 1
[12 31] [-1 -2] || [18 19] [-1 -1]
	time 24.0 18.0
	=> [-6. -5.] [-6. -5.]
	OUTSIDE
3 2
[12 31] [-1 -2] || [20 25] [-2 -2]
	time 11.0 14.0
	=> [-2.  3.] [-2.  3.]
	OUTSIDE
PAST 4 0 [20 19] [19 13]
PAST 4 1 [20 19] [18 19]
PAST 4 2 [20 19] [20 25]
PAST 4 3 [20 19] [12 31]


## True example

In [70]:
#k_min, k_max = 7, 27
k_min, k_max = 200000000000000, 400000000000000

cnt = 0
cntx = 0
for idx, (P1, V1) in enumerate(puzzle1):
    for jdx, (P2, V2) in enumerate(puzzle1[:idx]):
        # Check if y positions are differnet and if they go into the same direction
        DP = P2 - P1
        
        A0 = DP[1] / V1[1] - DP[0] / V2[0] * V2[1] / V1[1]
        A1 = 1 - V2[1] * V1[0] / (V1[1] * V2[0])
        
        
        if A1 == 0:
            continue
            
        b = A0 / A1
        a = (-DP[0] + b * V1[0])/V2[0]
        
        if (b < 0) | (a < 0):
            # No negative time allowed
            continue
            
        P1x = P1 + b * V1
        P2x = P2 + a * V2
        
        #if (P1x[0] >= k_min) & (P2x[0] >= k_min) & (P1x[1] <= k_max) & (P2x[1] <= k_max):
        if sum((P1x >= k_min) & (P1x <= k_max)) == 2:
            cnt += 1
            
        else:
            cntx += 1
            
print("Part 1: {}".format(cnt))

Part 1: 24627


# Part 2

Find the location of the rock + velocity that hits all hailstone ... on integer coordinates

## Check X first

In [98]:
PX = list(map(lambda x: x[0][0], puzzle))
VX = list(map(lambda x: x[1][0], puzzle))

PY = list(map(lambda x: x[0][1], puzzle))
VY = list(map(lambda x: x[1][1], puzzle))

PZ = list(map(lambda x: x[0][2], puzzle))
VZ = list(map(lambda x: x[1][2], puzzle))


# Résolution sur l'axe X seulement

## Get Velocity

Try multiple j

- VX: 148
- VY: 159
- VZ: 249

In [771]:
LST_mem = []

In [772]:
dim = 1

for j in range(40, 50):
    print(j)


    lst_extract = []
    for Pj, Vj in puzzle:
        lst_extract.append((Pj[dim], Vj[dim]))

    #X = np.array(sorted(lst_extract, key=lambda x: x[1]))
    X = np.array(lst_extract)

    V = sorted(set(np.arange(-600, 600)) - set(X[:, 0]))

    lst_success = []
    for v in  V:

        lst = []
        FLAG = True
        for i in range(len(X)):
            if i == j:
                continue

            xi = X[i, 0]
            xj = X[j, 0]
            dx = xj - xi
            dvi = X[i, 1] - v
            dvj = X[j, 1] - v

            lll = []
            for a in range(abs(dvi)+1):
                dd = dx + a * dvj
                if dd % dvi == 0:

                    lll.append((i, v,  dd / dvi, a, dvi))

            if len(lll) == 0:
                FLAG = False
                break
            else:
                lst.extend(lll)

        if FLAG:
            lst_success.append(v)
            #print("Success", v)

    LST_mem.append(lst_success)

40


/tmp/ipykernel_2027653/2366474338.py:34: RuntimeWarning: divide by zero encountered in long_scalars
  if dd % dvi == 0:
/tmp/ipykernel_2027653/2366474338.py:36: RuntimeWarning: divide by zero encountered in long_scalars
  lll.append((i, v,  dd / dvi, a, dvi))


41
42
43
44
45
46
47
48
49


##### Filter

In [773]:
S0 = set(LST_mem[0])
for s1 in LST_mem[1:]:
    S0 = S0 & set(s1)
    print(len(S0))
    
S0

19
8
3
1
1
1
1
1
1


{159}

## Get positions

In [774]:
Vsol = np.array([148, 159, 249])

In [775]:
P = []
V = []

for Pj, Vj in puzzle:
    P.append(Pj)
    V.append(Vj)
    
P = np.array(P)
V = np.array(V)


In [787]:
i = 1

DV = V - Vsol

for j in range(100):
    A = (P[i] - P[j]) / (DV[j])
    A = A[1] - A[0]

    B = DV[i] / DV[j]
    B = B[0] - B[1]

    ta = A / B
    print(ta)

870093641615.9999
nan
870093641615.9999
870093641616.0
870093641616.0001
870093641616.0
870093641616.0
870093641616.0002
870093641616.0
870093641616.0
870093641616.0001
870093641615.9998
870093641615.9988
870093641616.0001
870093641616.0001
870093641616.0
870093641616.0098
870093641616.0
870093641616.0002
870093641616.0001
870093641616.0
870093641616.0
870093641616.0
870093641616.0
870093641616.0
870093641616.0
870093641615.9967
870093641616.0001
870093641615.9999
870093641616.0002
870093641615.9999
870093641616.0
870093641615.9996
870093641616.0001
870093641615.9714
870093641616.0
870093641615.9999
870093641616.0
870093641615.9999
870093641615.9989
870093641615.9998
870093641616.0
870093641616.0001
870093641616.0
870093641615.9999
870093641615.9991
870093641615.9995
870093641615.9996
870093641616.0001
870093641616.0
870093641616.0
870093641616.0
870093641615.9998
870093641616.0001
870093641615.9998
870093641615.9998
870093641616.0001
870093641616.0
870093641616.0004
870093641616.0
870

/tmp/ipykernel_2027653/2602019537.py:12: RuntimeWarning: invalid value encountered in double_scalars
  ta = A / B
/tmp/ipykernel_2027653/2602019537.py:6: RuntimeWarning: divide by zero encountered in true_divide
  A = (P[i] - P[j]) / (DV[j])
/tmp/ipykernel_2027653/2602019537.py:9: RuntimeWarning: divide by zero encountered in true_divide
  B = DV[i] / DV[j]


In [ ]:
194723518367339, 181910661443432, 150675954587450

In [788]:
ta = 870093641616

XXX = P[i] + ta * (V[i] - Vsol)
XXX

array([194723518367339, 181910661443432, 150675954587450], dtype=int64)

In [789]:
sum(XXX)

527310134398221